spring.application.name=Todo-App-1



# = DataSource (MySQL)
# =============================
spring.datasource.url=jdbc:mysql://localhost:3306/taskflow
spring.datasource.username=root
spring.datasource.password=abced


# = JPA / Hibernate
# =============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false



# =============================
# = JWT (App Settings)
# =============================
# Change this to a long, random 256-bit secret (at least 32+ chars)
app.jwt.secret=uPZ4t9wS3Vx8QkL7mN2d0A1fJ8pR6sT9eW3yH4kB2vC7xZ1qM5nT8rL4pK9jD0h
# 24 hours (as per SRS NFR-06)
app.jwt.expiration-ms=86400000


# =============================
# = Admin bootstrap (single admin)
# =============================
app.admin.email=admin@taskflow.local
app.admin.password=Admin@123